[[steps]]
[steps.shell]
script = '''
set -e

# Format and mount "test" volume
mkfs.xfs /dev/sda
mount /dev/sda /mnt/test

cd xfstests-dev

cat << EOF > local.config
export TEST_DEV=/dev/sda
export TEST_DIR=/mnt/test
export SCRATCH_DEV=/dev/sdb
export SCRATCH_MNT=/mnt/scratch
EOF

# Convert any '_' back to '/'
./check "${TEST_NAME//_/\/}"
'''
